name: cgp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - seaborn
    - numpy
    - tqdm
    - fire
    - tensorboard
    - wandb
    - torch
    - torchvision
    - torch_optimizer
