## This is to check the Bayesian v/s MAP kernel hyperparameters.
method: grid
parameters:
  n_tasks:
    value: 10
  epochs:
    value: 500
  M:
    value: 100
  lr:
    value: 0.002
  batch_size:
    value: 512
  beta:
    value: 3.0
  map_est_hypers:
    values: [0, 1]
  seed:
    values: [1, 2, 3, 4, 5]
command:
  - ${env}
  - python3
  - /mnt/share/sanyam/src/continual_gp/experiments/mnist.py
  - p-mnist
  - --data-dir=/mnt/share/sanyam/datasets
  - ${args}
